//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDefterDemoProject.eDefter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="eDefter.ILedgerIntegration", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface ILedgerIntegration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedgerIntegration/UploadSource", ReplyAction="http://tempuri.org/ILedgerIntegration/UploadSourceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LedgerStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LedgerSourceStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        EDefterDemoProject.eDefter.StringResponse UploadSource(EDefterDemoProject.eDefter.LedgerSourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedgerIntegration/UploadSource", ReplyAction="http://tempuri.org/ILedgerIntegration/UploadSourceResponse")]
        System.Threading.Tasks.Task<EDefterDemoProject.eDefter.StringResponse> UploadSourceAsync(EDefterDemoProject.eDefter.LedgerSourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedgerIntegration/GetSourceInformation", ReplyAction="http://tempuri.org/ILedgerIntegration/GetSourceInformationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LedgerStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LedgerSourceStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        EDefterDemoProject.eDefter.ResponseOfLedgerSourceInformation GetSourceInformation(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedgerIntegration/GetSourceInformation", ReplyAction="http://tempuri.org/ILedgerIntegration/GetSourceInformationResponse")]
        System.Threading.Tasks.Task<EDefterDemoProject.eDefter.ResponseOfLedgerSourceInformation> GetSourceInformationAsync(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedgerIntegration/GetLedgerData", ReplyAction="http://tempuri.org/ILedgerIntegration/GetLedgerDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LedgerStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LedgerSourceStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        EDefterDemoProject.eDefter.ResponseOfLedgerData GetLedgerData(string identifier, bool certificateFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedgerIntegration/GetLedgerData", ReplyAction="http://tempuri.org/ILedgerIntegration/GetLedgerDataResponse")]
        System.Threading.Tasks.Task<EDefterDemoProject.eDefter.ResponseOfLedgerData> GetLedgerDataAsync(string identifier, bool certificateFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedgerIntegration/CancelLedgerSource", ReplyAction="http://tempuri.org/ILedgerIntegration/CancelLedgerSourceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LedgerStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LedgerSourceStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        EDefterDemoProject.eDefter.FlagResponse CancelLedgerSource(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedgerIntegration/CancelLedgerSource", ReplyAction="http://tempuri.org/ILedgerIntegration/CancelLedgerSourceResponse")]
        System.Threading.Tasks.Task<EDefterDemoProject.eDefter.FlagResponse> CancelLedgerSourceAsync(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedgerIntegration/CancelLedger", ReplyAction="http://tempuri.org/ILedgerIntegration/CancelLedgerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LedgerStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LedgerSourceStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        EDefterDemoProject.eDefter.FlagResponse CancelLedger(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedgerIntegration/CancelLedger", ReplyAction="http://tempuri.org/ILedgerIntegration/CancelLedgerResponse")]
        System.Threading.Tasks.Task<EDefterDemoProject.eDefter.FlagResponse> CancelLedgerAsync(string identifier);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LedgerSourceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] dataField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LedgerData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LedgerStatusWithLogInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LedgerStatusInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LedgerStatus statusField;
        
        private int statusCodeField;
        
        private string identifierField;
        
        private string documentIdField;
        
        private LedgerType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LedgerStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
                this.RaisePropertyChanged("DocumentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LedgerType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LedgerStatus {
        
        /// <remarks/>
        WaitingForBuild,
        
        /// <remarks/>
        Building,
        
        /// <remarks/>
        UnsignedFileReady,
        
        /// <remarks/>
        FileSigned,
        
        /// <remarks/>
        BeratGenerated,
        
        /// <remarks/>
        BeratSignedByCustomer,
        
        /// <remarks/>
        BeratReadyToSend,
        
        /// <remarks/>
        BeratSentToGIB,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Canceled,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LedgerType {
        
        /// <remarks/>
        Journal,
        
        /// <remarks/>
        Ledger,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LedgerData : LedgerStatusInfo {
        
        private string fileNameField;
        
        private byte[] dataField;
        
        private LedgerFileType fileTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LedgerFileType FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LedgerFileType {
        
        /// <remarks/>
        UnsignedLedgerFile,
        
        /// <remarks/>
        SignedLedgerFile,
        
        /// <remarks/>
        UnsignedCertificateFile,
        
        /// <remarks/>
        SignedCertificateFile,
        
        /// <remarks/>
        FinalCertificateFile,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LedgerStatusWithLogInfo : LedgerStatusInfo {
        
        private LogRecordItem[] logsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Logs", Order=0)]
        public LogRecordItem[] Logs {
            get {
                return this.logsField;
            }
            set {
                this.logsField = value;
                this.RaisePropertyChanged("Logs");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LogRecordItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string creatorField;
        
        private System.DateTime createDateUtcField;
        
        private string remoteIpAddressField;
        
        private string localIpAddressField;
        
        private string machineNameField;
        
        private byte typeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
                this.RaisePropertyChanged("Creator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CreateDateUtc {
            get {
                return this.createDateUtcField;
            }
            set {
                this.createDateUtcField = value;
                this.RaisePropertyChanged("CreateDateUtc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RemoteIpAddress {
            get {
                return this.remoteIpAddressField;
            }
            set {
                this.remoteIpAddressField = value;
                this.RaisePropertyChanged("RemoteIpAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LocalIpAddress {
            get {
                return this.localIpAddressField;
            }
            set {
                this.localIpAddressField = value;
                this.RaisePropertyChanged("LocalIpAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MachineName {
            get {
                return this.machineNameField;
            }
            set {
                this.machineNameField = value;
                this.RaisePropertyChanged("MachineName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LedgerSourceStatusWithLogInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LedgerSourceInformation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LedgerSourceStatusInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LedgerSourceStatus statusField;
        
        private int statusCodeField;
        
        private string identifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LedgerSourceStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LedgerSourceStatus {
        
        /// <remarks/>
        Waiting,
        
        /// <remarks/>
        Processing,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Canceled,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LedgerSourceInformation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LedgerSourceStatusWithLogInfo : LedgerSourceStatusInfo {
        
        private LogRecordItem[] logsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Logs", Order=0)]
        public LogRecordItem[] Logs {
            get {
                return this.logsField;
            }
            set {
                this.logsField = value;
                this.RaisePropertyChanged("Logs");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LedgerSourceInformation : LedgerSourceStatusWithLogInfo {
        
        private LedgerStatusWithLogInfo[] ledgersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ledgers", Order=0)]
        public LedgerStatusWithLogInfo[] Ledgers {
            get {
                return this.ledgersField;
            }
            set {
                this.ledgersField = value;
                this.RaisePropertyChanged("Ledgers");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FlagResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseOfLedgerData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseOfLedgerSourceInformation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isSuccededField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsSucceded {
            get {
                return this.isSuccededField;
            }
            set {
                this.isSuccededField = value;
                this.RaisePropertyChanged("IsSucceded");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FlagResponse : Response {
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseOfLedgerData : Response {
        
        private LedgerData valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LedgerData Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseOfLedgerSourceInformation : Response {
        
        private LedgerSourceInformation valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LedgerSourceInformation Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StringResponse : Response {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILedgerIntegrationChannel : EDefterDemoProject.eDefter.ILedgerIntegration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LedgerIntegrationClient : System.ServiceModel.ClientBase<EDefterDemoProject.eDefter.ILedgerIntegration>, EDefterDemoProject.eDefter.ILedgerIntegration {
        
        public LedgerIntegrationClient() {
        }
        
        public LedgerIntegrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LedgerIntegrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LedgerIntegrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LedgerIntegrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EDefterDemoProject.eDefter.StringResponse UploadSource(EDefterDemoProject.eDefter.LedgerSourceRequest request) {
            return base.Channel.UploadSource(request);
        }
        
        public System.Threading.Tasks.Task<EDefterDemoProject.eDefter.StringResponse> UploadSourceAsync(EDefterDemoProject.eDefter.LedgerSourceRequest request) {
            return base.Channel.UploadSourceAsync(request);
        }
        
        public EDefterDemoProject.eDefter.ResponseOfLedgerSourceInformation GetSourceInformation(string identifier) {
            return base.Channel.GetSourceInformation(identifier);
        }
        
        public System.Threading.Tasks.Task<EDefterDemoProject.eDefter.ResponseOfLedgerSourceInformation> GetSourceInformationAsync(string identifier) {
            return base.Channel.GetSourceInformationAsync(identifier);
        }
        
        public EDefterDemoProject.eDefter.ResponseOfLedgerData GetLedgerData(string identifier, bool certificateFile) {
            return base.Channel.GetLedgerData(identifier, certificateFile);
        }
        
        public System.Threading.Tasks.Task<EDefterDemoProject.eDefter.ResponseOfLedgerData> GetLedgerDataAsync(string identifier, bool certificateFile) {
            return base.Channel.GetLedgerDataAsync(identifier, certificateFile);
        }
        
        public EDefterDemoProject.eDefter.FlagResponse CancelLedgerSource(string identifier) {
            return base.Channel.CancelLedgerSource(identifier);
        }
        
        public System.Threading.Tasks.Task<EDefterDemoProject.eDefter.FlagResponse> CancelLedgerSourceAsync(string identifier) {
            return base.Channel.CancelLedgerSourceAsync(identifier);
        }
        
        public EDefterDemoProject.eDefter.FlagResponse CancelLedger(string identifier) {
            return base.Channel.CancelLedger(identifier);
        }
        
        public System.Threading.Tasks.Task<EDefterDemoProject.eDefter.FlagResponse> CancelLedgerAsync(string identifier) {
            return base.Channel.CancelLedgerAsync(identifier);
        }
    }
}
